const express = require('express')
const router = express.Router()
const { AddToSales, TotalRevenue, TotalQuantitySold, TopFiveProducts, RevenueByMonth, HighestQuantitySold,AveragePrice,  } = require('../controllers/salesController')
const {SellerAuthVerification, AvailableFor} = require('../middlewares/AuthVerification')

router.post('/add', SellerAuthVerification,  AddToSales)
router.get('/total-revenue', SellerAuthVerification, AvailableFor(["seller", "admin"]), TotalRevenue)  //Calculate and return the total revenue generated by all sales transactions.
router.get('/quantity-by-product',SellerAuthVerification, AvailableFor(["seller", "admin"]), TotalQuantitySold) //Find and return the total quantity sold for each product.
router.get('/top-products', SellerAuthVerification, AvailableFor(["seller", "admin"]), TopFiveProducts ) //Retrieve the top 5 products with the highest total revenue, along with their total revenue values.
router.get('/average-price', SellerAuthVerification, AvailableFor(["seller", "admin"]), AveragePrice) //Calculate and return the average price of products sold.
router.get('/revenue-by-month', SellerAuthVerification, AvailableFor(["seller", "admin"]), RevenueByMonth) //Group the sales data by month and year and calculate the total revenue for each month-year combination.
router.get('/highest-quantity-sold', SellerAuthVerification, AvailableFor(["seller", "admin"]), HighestQuantitySold) //Find and return the product that had the highest quantity sold on a single day.

module.exports = router;