const express = require('express')
const router = express.Router()

router.get('total-revenue')  //Calculate and return the total revenue generated by all sales transactions.
router.get('quantity-by-product') //Find and return the total quantity sold for each product.
router.get('top-products') //Retrieve the top 5 products with the highest total revenue, along with their total revenue values.
router.get('average-price') //Calculate and return the average price of products sold.
router.get('revenue-by-month') //Group the sales data by month and year and calculate the total revenue for each month-year combination.
router.get('highest-quantity-sold') //Find and return the product that had the highest quantity sold on a single day.
router.get('department-salary-expense') //Calculate and return the total salary expense for each department.

module.exports = router;